{% set goname = "github.com/gruntwork-io/terragrunt" %}
{% set version = "0.28.12" %}

{% set name = goname.split('/')[-1] %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://{{ goname }}/archive/v{{ version }}.tar.gz
  sha256: b9bedfd3ba49d51ee9dff323b448ad454556c32437533d264899fb65b2195aba

build:
  number: 0
  script:
    - go install -v -ldflags "-X main.VERSION={{ version }}" .

requirements:
  build:
    - {{ compiler('go') }}
  run:
    - terraform >=0.13.0,<0.15.0

test:
  commands:
    - {{ name|lower }} --version
    - {{ name|lower }} --help

about:
  home: https://www.gruntwork.io/
  license: MIT
  license_file: LICENSE.txt
  summary: Terragrunt is a thin wrapper for Terraform that provides extra tools for working with multiple Terraform modules.
  dev_url: https://github.com/gruntwork-io/terragrunt.git

extra:
  recipe-maintainers:
    - sodre
    - mariusvniekerk
    - hajapy
