{% set goname = "github.com/gruntwork-io/terragrunt" %}
{% set version = "0.19.31" %}

{% set name = goname.split('/')[-1] %}
{% set pkg_src = ('src/'+goname).replace("/",os.sep) %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  folder: {{ pkg_src }}
  url: https://{{ goname }}/archive/v{{version}}.tar.gz
  sha256: 42c0730f7b6c636413026289183e3ff4824fd494ea13a55df4b8f244b7650015 

build:
  number: 0
  script:
    - set -x
    - pushd {{ pkg_src }}
    - dep ensure -vendor-only
    - go install -v -ldflags "-X main.version={{ version }}" .

requirements:
  build:
    - {{ compiler('go') }}
    - go-dep

test:
  requires:
    - m2-bash  # [win]
  commands:
    - bash -c "{{ name|lower }} -v"
    - bash -c "{{ name|lower }} --help"

about:
  home: https://www.gruntwork.io/
  license: MIT
  license_file: {{ pkg_src }}/LICENSE.txt
  summary: Terragrunt is a thin wrapper for Terraform that provides extra tools for working with multiple Terraform modules.
  dev_url: https://github.com/gruntwork-io/terragrunt.git

extra:
  recipe-maintainers:
    - sodre
    - mariusvniekerk
