{% set goname = "github.com/gruntwork-io/terragrunt" %}
{% set version = "1.0.8" %}

{% set name = goname.split('/')[-1] %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://{{ goname }}/archive/v{{ version }}.tar.gz
  sha256: a5cdd3703944646d5d3cf2ee0b168e1b5b4873fa40fc0e558f59e9286455746d

build:
  number: 1

requirements:
  build:
    - {{ compiler('go') }}
  run:
    - terraform

test:
  requires:
    - fish  # [unix]
    - zsh   # [unix]
  commands:
    - {{ name|lower }} --version
    - {{ name|lower }} --help
    - test -f $PREFIX/etc/conda/activate.d/{{ name|lower }}_activate.sh        # [unix]
    - test -f $PREFIX/etc/conda/deactivate.d/{{ name|lower }}_deactivate.sh    # [unix]
    - test -f $PREFIX/etc/conda/activate.d/{{ name|lower }}_activate.fish      # [unix]
    - test -f $PREFIX/etc/conda/deactivate.d/{{ name|lower }}_deactivate.fish  # [unix]
    - bash -c 'source $PREFIX/etc/conda/activate.d/{{ name|lower }}_activate.sh && complete -p {{ name|lower }} | grep -q {{ name|lower }}'      # [unix]
    - zsh  -c 'source $PREFIX/etc/conda/activate.d/{{ name|lower }}_activate.sh && complete -p {{ name|lower }} | grep -q {{ name|lower }}'      # [unix]
    - fish -c 'source $PREFIX/etc/conda/activate.d/{{ name|lower }}_activate.fish; complete -c {{ name|lower }} | grep -q {{ name|lower }}'      # [unix]
    - if not exist "%PREFIX%\etc\conda\activate.d\{{ name|lower }}_activate.sh" exit 1        # [win]
    - if not exist "%PREFIX%\etc\conda\deactivate.d\{{ name|lower }}_deactivate.sh" exit 1    # [win]
    - if not exist "%PREFIX%\etc\conda\activate.d\{{ name|lower }}_activate.fish" exit 1      # [win]
    - if not exist "%PREFIX%\etc\conda\deactivate.d\{{ name|lower }}_deactivate.fish" exit 1  # [win]

about:
  home: https://www.gruntwork.io/
  license: MIT
  license_file: LICENSE.txt
  summary: Terragrunt is a thin wrapper for Terraform that provides extra tools for working with multiple Terraform modules.
  dev_url: https://github.com/gruntwork-io/terragrunt.git

extra:
  recipe-maintainers:
    - sodre
    - mariusvniekerk
    - hajapy
    - Hoeze
