{% set goname = "github.com/gruntwork-io/terragrunt" %}
{% set version = "0.57.2" %}

{% set name = goname.split('/')[-1] %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://{{ goname }}/archive/v{{ version }}.tar.gz
  sha256: f6fef3af7a16af93d0aaebbe3ae26d3503c0b3767621074e3894fb8caa2bdb6e

build:
  number: 0
  script:
    - go install -v -ldflags "-X main.VERSION={{ version }}" .

requirements:
  build:
    - {{ compiler('go') }}
  run:
    - terraform

test:
  commands:
    - {{ name|lower }} --version
    - {{ name|lower }} --help

about:
  home: https://www.gruntwork.io/
  license: MIT
  license_file: LICENSE.txt
  summary: Terragrunt is a thin wrapper for Terraform that provides extra tools for working with multiple Terraform modules.
  dev_url: https://github.com/gruntwork-io/terragrunt.git

extra:
  recipe-maintainers:
    - sodre
    - mariusvniekerk
    - hajapy
