{% set goname = "github.com/gruntwork-io/terragrunt" %}
{% set version = "0.29.9" %}

{% set name = goname.split('/')[-1] %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://{{ goname }}/archive/v{{ version }}.tar.gz
  sha256: fc4d608f19d9abba8708b76604978f419f0df7a7e5099785e1ce1a83af1be218

build:
  number: 0
  script:
    - go install -v -ldflags "-X main.VERSION={{ version }}" .

requirements:
  build:
    - {{ compiler('go') }}
  run:
    - terraform >=0.15.1,<0.16.0

test:
  commands:
    - {{ name|lower }} --version
    - {{ name|lower }} --help

about:
  home: https://www.gruntwork.io/
  license: MIT
  license_file: LICENSE.txt
  summary: Terragrunt is a thin wrapper for Terraform that provides extra tools for working with multiple Terraform modules.
  dev_url: https://github.com/gruntwork-io/terragrunt.git

extra:
  recipe-maintainers:
    - sodre
    - mariusvniekerk
    - hajapy
