travis:
  secure:
    BINSTAR_TOKEN: Z3bmfw/VdaISVD9BtBnSmY/oy7XPc8eBEgJBWsGZL5q9cU/brY3pe4TvB6B1c8n6Zz+RBXiWACY62L05v/ZcFIBZ3R/rzEhQGjRwUnYt/bHJmHCL1M07Y+ygwpRJB9yurEC6dpujKxliO3WMURGEvoC8eZEAZ3uccL/hwvBfaKMeMnEKv4n650lsU9RTGb6BxJKo1XXbkyd3IgrMoUP/nCa+RD+AXlRETXSmOKHPlJ46jKfEEjqS9pApPZIo17gYsbZddi11mGQ3znL/W123My5N532KMoIfbGafPSC6/WJiC91MkF4CgVdg4dQdK91DMIPmhivW7q0Y013FpLeo14CwbX+ul0SNfA1X/zPLANsTCiZ9U35mGAuSl8G9FteTWHFb/fbyHhR39OQaYLniiIHNXraS5W9vkBZG9lDEDdufKkR3BOzJSlaxtqT8hrt+e675tUV9W4nrZ04P6U9aLLzfQb1IZfS9b90H70g+4CDot6XbIO77L+POkkNSaDaWQXGiN6Q3J7PzmQCVVMjBNUL7t4gUHOzI1XtI3bp1SC2N2lJFaNTN0e26efIjTTKlGn6klYvGu7LirZ1jfON8bVffvFvuHkjlaHo10kkRQqj5+uht/JkNj0XdUmNUMRTJ3YuU5T6xldu50s0/aQtbpNEEsT9whRPkiapO2yyOiok=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
bot:
  automerge: true
